import {auth,functions} from '../src/firebase.js';
import {signInWithEmailAndPassword,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import {httpsCallable} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js';
import {doc,getDoc} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import {db} from '../src/firebase.js';
const status=document.querySelector('#status'), result=document.querySelector('#result'); const confirmEntry=httpsCallable(functions,'confirmEntry'); let scanner;
document.querySelector('#login').onclick=async()=>{try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(e){status.className='status error';status.textContent='Invalid operator credentials.'}};
onAuthStateChanged(auth,async u=>{if(!u)return;const me=await getDoc(doc(db,'scannerOperators',u.uid));if(!me.exists()){status.className='status error';status.textContent='This account is not a scanner operator.';return}gate.value=me.data().gate;document.querySelector('#loginPanel').style.display='none';document.querySelector('#scannerPanel').style.display='block';start()});
function start(){scanner=new Html5Qrcode('reader');scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},async text=>{await scanner.pause(true);show(text)}).catch(e=>{result.className='status error';result.textContent='Camera unavailable. Check browser camera permission.'})}
async function show(payload){result.className='status';result.textContent='Checking ticket…';try{const r=await confirmEntry({mode:'CHECK',qrPayload:payload,night:Number(night.value),gate:gate.value});const t=r.data;if(t.result!=='VALID'){result.className='status error';result.innerHTML=`<b>ENTRY DENIED</b><br>${t.message}<div class="actions"><button class="btn" id="again">Scan Again</button></div>`;again.onclick=()=>scanner.resume();return}result.className='status success';result.innerHTML=`<h2 style="margin:0 0 8px">VALID TICKET</h2><b>${escapeHtml(t.name)}</b><br><span class="small">Batch ${escapeHtml(t.batch)} · Ticket ${escapeHtml(t.ticketId)}</span><div class="actions"><button class="btn primary" id="confirm">Confirm Entry</button><button class="btn" id="again">Cancel</button></div>`;again.onclick=()=>{result.innerHTML='';scanner.resume()};confirm.onclick=async()=>{confirm.disabled=true;try{const done=await confirmEntry({mode:'CONFIRM',qrPayload:payload,night:Number(night.value),gate:gate.value});result.className='status success';result.innerHTML='<h2 style="margin:0">ENTRY CONFIRMED ✓</h2><p>Ticket marked used for this night.</p><button class="btn primary" id="again2">Scan Next</button>';again2.onclick=()=>{result.innerHTML='';scanner.resume()}}catch(e){confirm.disabled=false;result.className='status error';result.textContent=e.message||'Could not confirm entry.'}}}catch(e){result.className='status error';result.textContent=e.message||'Ticket check failed.';setTimeout(()=>scanner.resume(),1200)}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
