import { auth,db,functions } from '../src/firebase.js';
import { signInWithEmailAndPassword,onAuthStateChanged,signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { doc,getDoc,collection,query,where,getDocs,orderBy } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { httpsCallable } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js';
const st=document.querySelector('#status'), dash=document.querySelector('#dashboard'); const verify=httpsCallable(functions,'verifyPayment'); const reject=httpsCallable(functions,'rejectPayment');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
document.querySelector('#login').onclick=async()=>{st.className='status';st.textContent='Signing in…';try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(e){st.className='status error';st.textContent='Invalid CR credentials.'}};
onAuthStateChanged(auth,async u=>{if(!u)return;const me=await getDoc(doc(db,'crs',u.uid));if(!me.exists()){await signOut(auth);st.className='status error';st.textContent='This account is not assigned as a CR.';return}const batch=me.data().batch;document.querySelector('#loginPanel').style.display='none';load(batch)});
async function load(batch){dash.innerHTML=`<div class="stat-grid"><div class="stat"><span class="small">Assigned batch</span><strong>${esc(batch)}</strong></div><div class="stat"><span class="small">Portal</span><strong>CR</strong></div></div><section class="panel"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><p class="eyebrow">PENDING PAYMENTS</p><h2>Check UTRs</h2></div><button class="btn" id="logout">Sign out</button></div><div id="list" class="table-wrap">Loading…</div></section>`;document.querySelector('#logout').onclick=()=>signOut(auth);const q=query(collection(db,'registrations'),where('batch','==',batch),where('paymentStatus','==','PENDING'));const snap=await getDocs(q);const list=document.querySelector('#list');if(snap.empty){list.innerHTML='<div class="status success">No pending payments.</div>';return}let html='<table class="table"><thead><tr><th>Student</th><th>UTR</th><th>Amount</th><th>Paid to</th><th>Action</th></tr></thead><tbody>';snap.forEach(d=>{const x=d.data();html+=`<tr><td><b>${esc(x.name)}</b><br><span class="small">${esc(x.rollNumber)} · ${esc(x.mobile)}</span></td><td>${esc(x.utr)}</td><td>₹${esc(x.amount)}</td><td>${esc(x.crName)}</td><td><button class="btn success" data-v="${d.id}">Verify</button> <button class="btn danger" data-r="${d.id}">Reject</button></td></tr>`});html+='</tbody></table>';list.innerHTML=html;list.querySelectorAll('[data-v]').forEach(b=>b.onclick=async()=>act(b.dataset.v,true,b));list.querySelectorAll('[data-r]').forEach(b=>b.onclick=async()=>act(b.dataset.r,false,b));}
async function act(id,ok,b){b.disabled=true;try{const r=ok?await verify({registrationId:id}):await reject({registrationId:id});alert(ok?'Payment verified. Ticket generated.':'Payment rejected.');const me=await getDoc(doc(db,'crs',auth.currentUser.uid));load(me.data().batch)}catch(e){alert(e.message||'Action failed.');b.disabled=false}}
