const {onCall,onRequest,HttpsError}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const syncSecret=defineSecret('SYNC_SECRET');
const {setGlobalOptions}=require('firebase-functions/v2/options');
const admin=require('firebase-admin');
const crypto=require('crypto');
admin.initializeApp();
setGlobalOptions({region:'asia-south1',maxInstances:10});
const db=admin.firestore();
const FieldValue=admin.firestore.FieldValue;
const BATCHES=['2021','2022','2023','2024','2025','2026','OTHERS'];
function randomToken(){return crypto.randomBytes(32).toString('base64url')}
function ticketId(){return 'INS-'+crypto.randomBytes(5).toString('hex').toUpperCase()}
function qrPayload(token){return `INSOMNIA|v1|${token}`}
function requireAuth(ctx){if(!ctx.auth)throw new HttpsError('unauthenticated','Sign in required.')}
async function getRole(uid){const [a,c,s]=await Promise.all([db.doc(`admins/${uid}`).get(),db.doc(`crs/${uid}`).get(),db.doc(`scannerOperators/${uid}`).get()]);if(a.exists)return{role:'admin',data:a.data()};if(c.exists)return{role:'cr',data:c.data()};if(s.exists)return{role:'scanner',data:s.data()};return null}
exports.syncRegistration=onRequest({cors:false,secrets:[syncSecret]},async(req,res)=>{try{if(req.method!=='POST')return res.status(405).json({error:'POST only'});const secret=req.get('x-insomnia-sync-secret');if(!secret||secret!==syncSecret.value())return res.status(401).json({error:'Unauthorized'});const x=req.body||{};for(const k of ['name','mobile','email','batch','utr','amount','crName'])if(!String(x[k]||'').trim())return res.status(400).json({error:`Missing ${k}`});const batch=String(x.batch).trim();if(!BATCHES.includes(batch))return res.status(400).json({error:'Invalid batch'});const ref=db.collection('registrations').doc();const registrationId='INS-R-'+crypto.randomBytes(4).toString('hex').toUpperCase();await ref.set({registrationId,name:String(x.name).trim(),mobile:String(x.mobile).trim(),email:String(x.email).trim(),rollNumber:String(x.rollNumber||'').trim(),batch,utr:String(x.utr).trim(),amount:String(x.amount||'').trim(),crName:String(x.crName).trim(),paymentScreenshotUrl:String(x.paymentScreenshotUrl||'').trim(),paymentStatus:'PENDING',ticketIssued:false,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await db.collection('auditLogs').add({type:'REGISTRATION_CREATED',registrationId,source:'GOOGLE_FORM',timestamp:FieldValue.serverTimestamp()});return res.json({ok:true,registrationId})}catch(e){console.error(e);return res.status(500).json({error:'Sync failed'})}});
exports.verifyPayment=onCall(async ctx=>{requireAuth(ctx);const role=await getRole(ctx.auth.uid);if(!role||role.role!=='cr')throw new HttpsError('permission-denied','CR access required.');const id=String(ctx.data?.registrationId||'');if(!id)throw new HttpsError('invalid-argument','Registration ID required.');const ref=db.collection('registrations').doc(id);const ticketRef=db.collection('tickets').doc(id);let out;await db.runTransaction(async tx=>{const r=await tx.get(ref);if(!r.exists)throw new HttpsError('not-found','Registration not found.');const x=r.data();if(String(x.batch)!==String(role.data.batch))throw new HttpsError('permission-denied','This registration is outside your assigned batch.');if(x.paymentStatus==='VERIFIED'){out={ticketId:x.ticketId};return}if(x.paymentStatus!=='PENDING')throw new HttpsError('failed-precondition','Registration is no longer pending.');const token=randomToken();const tid=ticketId();const now=FieldValue.serverTimestamp();tx.update(ref,{paymentStatus:'VERIFIED',verifiedBy:ctx.auth.uid,verifiedAt:now,ticketIssued:true,ticketId:tid,updatedAt:now});tx.set(ticketRef,{registrationId:id,ticketId:tid,secureToken:token,name:x.name,rollNumber:x.rollNumber||'',mobile:x.mobile,batch:x.batch,email:x.email,qrPayload:qrPayload(token),active:true,createdAt:now,night1:'UNUSED',night2:'UNUSED',night3:'UNUSED'});tx.set(db.collection('auditLogs').doc(),{type:'PAYMENT_VERIFIED',registrationId:id,ticketId:tid,operatorUid:ctx.auth.uid,timestamp:now});out={ticketId:tid}});return out});
exports.rejectPayment=onCall(async ctx=>{requireAuth(ctx);const role=await getRole(ctx.auth.uid);if(!role||role.role!=='cr')throw new HttpsError('permission-denied','CR access required.');const id=String(ctx.data?.registrationId||'');const reason=String(ctx.data?.reason||'Payment not verified');const ref=db.collection('registrations').doc(id);await db.runTransaction(async tx=>{const r=await tx.get(ref);if(!r.exists)throw new HttpsError('not-found','Registration not found.');const x=r.data();if(String(x.batch)!==String(role.data.batch))throw new HttpsError('permission-denied','Outside assigned batch.');if(x.paymentStatus!=='PENDING')throw new HttpsError('failed-precondition','Registration is no longer pending.');tx.update(ref,{paymentStatus:'REJECTED',rejectionReason:reason,rejectedBy:ctx.auth.uid,rejectedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});tx.set(db.collection('auditLogs').doc(),{type:'PAYMENT_REJECTED',registrationId:id,reason,operatorUid:ctx.auth.uid,timestamp:FieldValue.serverTimestamp()})});return{ok:true}});
exports.retrieveTicket=onCall(async ctx=>{const mobile=String(ctx.data?.mobile||'').trim();const utr=String(ctx.data?.utr||'').trim();if(!mobile||!utr)throw new HttpsError('invalid-argument','Mobile number and UTR are required.');const snap=await db.collection('registrations').where('mobile','==',mobile).where('utr','==',utr).limit(1).get();if(snap.empty)return{available:false};const r=snap.docs[0].data();if(r.paymentStatus!=='VERIFIED'||!r.ticketIssued)return{available:false};const t=await db.doc(`tickets/${snap.docs[0].id}`).get();if(!t.exists||!t.data().active)return{available:false};const x=t.data();return{available:true,name:x.name,rollNumber:x.rollNumber,batch:x.batch,ticketId:x.ticketId,qrPayload:x.qrPayload}});
exports.confirmEntry=onCall(async ctx=>{requireAuth(ctx);const role=await getRole(ctx.auth.uid);if(!role||role.role!=='scanner')throw new HttpsError('permission-denied','Scanner access required.');const mode=String(ctx.data?.mode||'CHECK');const payload=String(ctx.data?.qrPayload||'');const night=Number(ctx.data?.night);const gate=String(ctx.data?.gate||'');if(![1,2,3].includes(night)||!['BOYS','GIRLS'].includes(gate))throw new HttpsError('invalid-argument','Invalid night or gate.');if(role.data.gate!==gate)throw new HttpsError('permission-denied','This scanner is assigned to a different gate.');if(!payload.startsWith('INSOMNIA|v1|'))return{result:'INVALID',message:'Invalid QR format.'};const token=payload.split('|')[2];if(!token)return{result:'INVALID',message:'Invalid QR token.'};const snap=await db.collection('tickets').where('secureToken','==',token).limit(1).get();if(snap.empty)return{result:'INVALID',message:'Ticket not found.'};const ref=snap.docs[0].ref;const current=snap.docs[0].data();const field=`night${night}`;if(mode==='CHECK'){if(!current.active)return{result:'INVALID',message:'Ticket is inactive.'};if(current[field]==='USED')return{result:'USED',message:`Ticket already used for Night ${String(night).padStart(2,'0')}.`};const reg=await db.doc(`registrations/${current.registrationId}`).get();if(!reg.exists||reg.data().paymentStatus!=='VERIFIED')return{result:'INVALID',message:'Payment is not verified.'};return{result:'VALID',name:current.name,batch:current.batch,ticketId:current.ticketId}}if(mode!=='CONFIRM')throw new HttpsError('invalid-argument','Invalid scan mode.');let out;await db.runTransaction(async tx=>{const t=await tx.get(ref);if(!t.exists)throw new HttpsError('not-found','Ticket not found.');const x=t.data();if(!x.active)throw new HttpsError('failed-precondition','Ticket is inactive.');if(x[field]==='USED')throw new HttpsError('already-exists',`Ticket already used for Night ${String(night).padStart(2,'0')}.`);const reg=await tx.get(db.doc(`registrations/${x.registrationId}`));if(!reg.exists||reg.data().paymentStatus!=='VERIFIED')throw new HttpsError('failed-precondition','Payment is not verified.');tx.update(ref,{[field]:'USED',updatedAt:FieldValue.serverTimestamp()});tx.set(db.collection('entryLogs').doc(),{ticketId:x.ticketId,registrationId:x.registrationId,night,gate,operatorUid:ctx.auth.uid,result:'ENTRY_CONFIRMED',timestamp:FieldValue.serverTimestamp()});tx.set(db.collection('auditLogs').doc(),{type:'ENTRY_CONFIRMED',ticketId:x.ticketId,registrationId:x.registrationId,night,gate,operatorUid:ctx.auth.uid,timestamp:FieldValue.serverTimestamp()});out={ok:true}});return out});
exports.createCr=onCall(async ctx=>{requireAuth(ctx);const role=await getRole(ctx.auth.uid);if(!role||role.role!=='admin')throw new HttpsError('permission-denied','Admin access required.');const email=String(ctx.data?.email||'').trim();const password=String(ctx.data?.password||'');const batch=String(ctx.data?.batch||'');const name=String(ctx.data?.name||'').trim();if(!email||password.length<8||!BATCHES.includes(batch))throw new HttpsError('invalid-argument','Valid email, 8+ character password and batch are required.');const user=await admin.auth().createUser({email,password,displayName:name});await db.doc(`crs/${user.uid}`).set({role:'cr',batch,name,email,active:true,createdAt:FieldValue.serverTimestamp()});return{uid:user.uid}});
exports.createScanner=onCall(async ctx=>{requireAuth(ctx);const role=await getRole(ctx.auth.uid);if(!role||role.role!=='admin')throw new HttpsError('permission-denied','Admin access required.');const email=String(ctx.data?.email||'').trim();const password=String(ctx.data?.password||'');const gate=String(ctx.data?.gate||'');if(password.length<8||!email||!['BOYS','GIRLS'].includes(gate))throw new HttpsError('invalid-argument','Invalid scanner details.');const user=await admin.auth().createUser({email,password});await db.doc(`scannerOperators/${user.uid}`).set({role:'scanner',gate,active:true,email,createdAt:FieldValue.serverTimestamp()});return{uid:user.uid}});
