import {auth,db,functions} from '../src/firebase.js';
import{signInWithEmailAndPassword,onAuthStateChanged,signOut}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{collection,getDocs}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{httpsCallable}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js';
const st=document.querySelector('#status'),dash=document.querySelector('#dash');const createCr=httpsCallable(functions,'createCr'),createScanner=httpsCallable(functions,'createScanner');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
login.onclick=async()=>{try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(e){st.className='status error';st.textContent='Invalid admin credentials.'}};onAuthStateChanged(auth,async u=>{if(!u)return;document.querySelector('#loginPanel').style.display='none';await load()});
async function load(){const snap=await getDocs(collection(db,'registrations'));let p=0,v=0,r=0;const rows=[];snap.forEach(d=>{const x=d.data();if(x.paymentStatus==='PENDING')p++;if(x.paymentStatus==='VERIFIED')v++;if(x.paymentStatus==='REJECTED')r++;rows.push({id:d.id,...x})});dash.innerHTML=`<div class="stat-grid"><div class="stat"><span class="small">Registrations</span><strong>${rows.length}</strong></div><div class="stat"><span class="small">Pending</span><strong>${p}</strong></div><div class="stat"><span class="small">Verified</span><strong>${v}</strong></div><div class="stat"><span class="small">Rejected</span><strong>${r}</strong></div></div><section class="panel"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><p class="eyebrow">ADMIN</p><h2>System setup</h2></div><button class="btn" id="logout">Sign out</button></div><div class="grid"><div class="field col-4"><label>CR email</label><input id="crEmail" type="email"></div><div class="field col-4"><label>Temporary password</label><input id="crPass" type="password" placeholder="8+ characters"></div><div class="field col-4"><label>CR batch</label><select id="crBatch">${['2021','2022','2023','2024','2025','2026','OTHERS'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field col-12"><label>CR name</label><input id="crName"></div></div><div class="actions"><button class="btn primary" id="makeCr">Create CR</button></div><hr style="border-color:var(--line);border-width:1px 0 0;margin:26px 0"><div class="grid"><div class="field col-4"><label>Scanner email</label><input id="scEmail" type="email"></div><div class="field col-4"><label>Temporary password</label><input id="scPass" type="password" placeholder="8+ characters"></div><div class="field col-4"><label>Assigned gate</label><select id="scGate"><option>BOYS</option><option>GIRLS</option></select></div></div><div class="actions"><button class="btn" id="makeScanner">Create Scanner</button><button class="btn" id="export">Export registrations CSV</button></div></section><section class="panel"><p class="eyebrow">REGISTRATIONS</p><h2>Latest records</h2><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Batch</th><th>UTR</th><th>CR</th><th>Status</th></tr></thead><tbody>${rows.slice(-100).reverse().map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="small">${esc(x.mobile)} · ${esc(x.rollNumber)}</span></td><td>${esc(x.batch)}</td><td>${esc(x.utr)}</td><td>${esc(x.crName)}</td><td><span class="badge ${x.paymentStatus.toLowerCase()}">${esc(x.paymentStatus)}</span></td></tr>`).join('')}</tbody></table></div></section>`;
logout.onclick=()=>signOut(auth);makeCr.onclick=async()=>{try{await createCr({email:crEmail.value,password:crPass.value,batch:crBatch.value,name:crName.value});alert('CR created.');}catch(e){alert(e.message)}};makeScanner.onclick=async()=>{try{await createScanner({email:scEmail.value,password:scPass.value,gate:scGate.value});alert('Scanner created.');}catch(e){alert(e.message)}};export.onclick=()=>downloadCSV(rows)}
function downloadCSV(rows){const cols=['id','name','rollNumber','mobile','email','batch','crName','utr','amount','paymentStatus','ticketId'];const csv=[cols.join(','),...rows.map(r=>cols.map(c=>'"'+String(r[c]??'').replace(/"/g,'""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='insomnia-registrations.csv';a.click();URL.revokeObjectURL(a.href)}
